### ISSUE TITLE
[jobs] shortcode order argument stuck in ASC

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/remotejobs#1]
I've been attempting to modify the order of jobs within the [jobs] shortcode to no avail. Changing the arguments seems to have no affect on the order.

**Comment by chriswallace** [comment]
@christianc1 you said this week you’d have this sorting issue resolved for RemoteJobs.com… any progress here?

**Comment by christianc1** [comment]
@chriswallace Please confirm on production

**Comment by christianc1** [comment]
Closing, fixed.
