### ISSUE TITLE
People get empty job alert emails every day.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/remotejobs#2]
I've gotten some reports that people are getting empty emails every day. They shouldn't receive any emails if there are matching jobs for their alerts.

**Comment by chriswallace** [comment]
Hey @christianc1, have you taken a look at this yet? Need to get it fixed or we risk losing some subscribers to our email alerts.

**Comment by christianc1** [comment]
Sorry missed this.  I'll take a look this afternoon.

**Comment by christianc1** [comment]
This should do it: http://lift.d.pr/1gxcT/3pw8ox1V  Attn @chriswallace
